# -*- coding: utf-8 -*-
"""Week 2 Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9Kl5UEVVoQY9_MCBMjsJrql2GuCPhJC
"""

# Number 1
# Creating an Empty List
my_list =[]

# Number 2
#Appending elements
my_list = [10, 20, 30, 40, 40]
my_list

# Number 3
# Insert value
my_list.insert(1, 15)
my_list

# Number 4
# Extend the list with another list
new_list = [50, 60, 70]
my_list.extend(new_list)
my_list

# Number 5
# Remove the last element
my_list.remove(70)
my_list

# Number 6
# Sort in ascending
my_list.sort()
my_list

# print the index
print(my_list.index(30))